services:
  backend:
    build: ./backend
    container_name: scheduly-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - scheduly-network

  frontend:
    build: ./frontend
    container_name: scheduly-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - scheduly-network

  mongo:
    image: mongo:latest
    container_name: scheduly-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - scheduly-network

networks:
  scheduly-network:
    driver: bridge

volumes:
  mongo-data: